name: master

on:
  push:
    branch:
      - master
  schedule:
    - cron: '* * * * *' 

jobs:
  bulid:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1 
      - name: Running
        run: |
          echo "Running"
